- .github/workflows/pull_request.yml
> PR 워크플로 설정

- src/components/common/SpaceMemberList/SpaceMemberList.tsx
- src/components/common/SpaceMemberList/constants/index.ts
- src/components/index.ts
- src/data/index.ts
#41 
- SpaceMemberList 컴포넌트를 구현하였습니다.
```ts
interface Member {
id: number
name: string
profile: string
auth: string
}
interface SpaceMemberListProps {
members: Member[] // 스페이스의 멤버 리스트 데이터
edit?: boolean // 스페이스 상세 화면(false)인지 세팅 화면(true)인지에 대한 여부, default: false
}
```
```tsx
import { SpaceMemberList } from '@/components'
import { mock_memberData } from '@/data'
export default function Home() {
const memberData = mock_memberData
return (
<>
<SpaceMemberList
members={memberData}
edit={true}
/>
</>
)
}
```
> 스페이스 멤버 컴포넌트 구현

- src/components/common/Dropdown/Dropdown.tsx
- src/components/common/Dropdown/hooks/useDropdown.ts
- close #58 
- 모달에서 클릭했을 때 옵션이 안 보이는 버그를 수정했습니다.
- dropdownRef를 옵션 div에서 드롭다운 전체 div로 수정
https://github.com/Team-TenTen/LinkHub-FE/assets/49032882/84dafe56-d87d-4b3a-8ddb-99206dfcdb3f
> Dropdown 컴포넌트 버그 수정

- .github/workflows/deploy.yml
- .github/workflows/pull_request.yml
> CI/CD 워크플로 수정

- .github/workflows/deploy.yml
- .github/workflows/pull_request.yml
> [Release] v0.1.2

- .github/workflows/deploy.yml
> CI/CD Test

- src/types/index.ts
Closes #98 
API req/res interface를 작성했습니다.
기존 컴포넌트에 적용할 만한 타입을 적용하려다가 수정할 부분이 너무 많을 것 같아 타입만 선언했습니다.
> API req/res interface 작성

- src/app/api/link/route.ts
- src/app/api/meta/route.ts
- src/components/common/LinkList/LinkList.tsx
- src/components/common/LinkList/constants/index.ts
- src/components/common/LinkList/hooks/useCreateLink.ts
- src/components/common/Modal/Modal.tsx
- src/components/common/Modal/hooks/useModalLogic.ts
- src/constants/index.ts
- src/services/link/link.ts
- src/services/meta/meta.ts
- src/types/index.ts
- src/utils/index.ts
#97 
- 링크 생성 api를 구현 및 연결하였습니다.
- Meta data를 불러오는 api를 구현 및 연결하였습니다.
1. page에서 services 폴더 내부의 api 호출
2. services 폴더 내부에서 api 폴더 내부의 api 호출
3. 응답 데이터를 page로 반환
<br>
api를 호출하는 부분에서 통일되었으면 하는 부분들을 추가 설명해 드리겠습니다!
- services에서 호출하는 함수명은 fetch + 동사 + 명사로 작성하였습니다.
- 호출 매개변수들을 변수로 미리 생성하고 넣어주는 방식으로 작성하였습니다. (path, body, authorization 등...)
- services에서 호출하는 함수에서 실제 전달되는 body의 타입과 더불어 spaceId를 추가로 전달하여 CreateLinkReqBody을 상속받아  Fetch + 함수명 + Props 라는 타입으로 정의하였습니다.
<br>
```tsx
import { CreateLinkReqBody } from '@/types'
import { apiClient } from '../apiServices'
export interface FetchCreateLinkProps extends CreateLinkReqBody {
spaceId: number
}
const fetchCreateLink = async ({
spaceId,
url,
title,
tag,
color,
}: FetchCreateLinkProps) => {
const path = '/api/link' // api 폴더 내부의 경로
const body = { …
```
> 링크 생성 api 연결

- .github/workflows/deploy.yml
> [Release] v0.1.1

- src/app/api/registerUser/route.ts
Closes #157 
```typescript
// 수정전
export async function POST(request: NextRequest) {
const body = await request.formData()
const path = `/members/join`
try {
const response = await apiServer.post(path, body, {}, {}, 'multipart')
return NextResponse.json(response)
} catch (error: any) {
return NextResponse.json(
{ error: error.response.data.message },
{ status: error.response.status },
)
}
}
// 수정 후
export async function POST(request: NextRequest) {
const body = await request.formData()
const path = `/members/join`
try {
const response = await apiServer.post(path, body, {}, {}, 'multipart')
return response
} catch (error: any) {
return NextResponse.json(
{ error: error.response.data.message },
{ status: error.response.status },
)
}
}
```
> 회원가입 오류 수정 (긴급)

- src/components/common/Sidebar/Sidebar.tsx
- src/components/common/Sidebar/hooks/useMySpace.ts
> 사이드바 즐겨찾기 스페이스 api 연결

- package-lock.json
- package.json
- src/app/layout.tsx
- src/components/Space/SpaceForm.tsx
- src/components/common/Toast/Toast.tsx
- src/components/common/Toast/ToastContainer.tsx
Closes #177 
```typescript
const handleConfirm = async () => {
try {
await fetchDeleteSpace(spaceId)
notify('info', '스페이스가 삭제되었습니다.')
router.replace('/')
} catch (e) {
notify('error', '스페이스 삭제에 실패하였습니다.')
}
}
```
> 토스트 컴포넌트 구현

- src/app/layout.tsx
- src/components/common/Header/Header.tsx
- src/components/common/Sidebar/Sidebar.tsx
- src/components/common/Sidebar/hooks/useSidebar.ts
- tailwind.config.ts
- close #193 
- 사이드바 애니메이션을 구현했습니다.
- `animation-duration: 0.4s`
https://github.com/Team-TenTen/LinkHub-FE/assets/49032882/6d06a082-544a-451f-9863-66f2d952bfac
- 공통 레이아웃 min-height, shadow를 추가했습니다.
> 사이드바 애니메이션 구현

- src/components/common/Sidebar/Sidebar.tsx
#200
- 사이드바가 두번 렌더링 되는 오류를 수정하였습니다.
> 사이드바 렌더링 오류 수정

- src/app/api/user/[memberId]/spaces/route.ts
- 본인의 비공개 스페이스가 보이지 않는 문제를 수정하였습니다.
> 본인의 비공개 스페이스가 보이지 않는 오류 수정

- src/app/layout.tsx
#214 
모바일에서 인풋 클릭 시 확대되지 않도록 메타 태그를 추가하였습니다.
```tsx
<head>
<meta
name="viewport"
content="width=device-width, initial-scale=1.0, user-scalable=no"
/>
</head>
```
토요일에 배포 후 모바일에서 테스트를 해봐야 할 것 같네요!
> 모바일에서 인풋 클릭 시 줌인되는 현상 수정

- src/components/common/SpaceMemberList/SpaceMemberList.tsx
- close #210 
- 스페이스 초대 시 토스트를 적용했습니다.
- 라이팅 수정 의견 있으면 남겨주세요!
https://github.com/Team-TenTen/LinkHub-FE/assets/49032882/90ecee3c-271e-4f7a-8449-6ebb8f04484e
> 스페이스 초대 토스트 적용

- src/lib/contexts/AuthProvider.tsx
- src/lib/fetchAPI.ts
- src/middleware.ts
> 에러처리 수정 및 접근 제한 추가

- src/components/common/Comment/Comment.tsx
- src/components/common/Dropdown/Dropdown.tsx
- src/components/common/Input/Input.tsx
- close #245 
- Dropdown 컴포넌트에서 `제거` 항목을 위한 danger prop을 임시 제거했습니다.
- 태그가 많을 경우를 고려해 Dropdown 컴포넌트 max-height, overflow 를 추가했습니다.
https://github.com/Team-TenTen/LinkHub-FE/assets/49032882/7912dedc-8f02-494c-99f9-93e27d30627e
- 검색창에서 드롭다운과 있으면 일정 크기 이하로 줄어들지 않아서 input size 속성을 15로 수정했습니다. (default: 20)
> Dropdown, Comment 컴포넌트 UI 수정

- src/components/SearchController/SearchController.tsx
- src/components/UserList/UserList.tsx
- src/components/common/CategoryList/CategoryListItem.tsx
- src/components/common/Space/Space.tsx
- close #257 
- 카테고리 리스트 컴포넌트 버그를 수정했습니다.
https://github.com/Team-TenTen/LinkHub-FE/assets/49032882/083b336f-4755-4518-ba8c-2f75b4308e8d
- Space 컴포넌트에서 가져오기 한 스페이스인 경우 아이콘 색상을 변경했습니다.
> CategoryList 컴포넌트 버그 수정

- src/components/common/Sidebar/Sidebar.tsx
- #270 
- Sidebar 컴포넌트 스타일 수정했습니다.
> Sidebar 컴포넌트 스타일 수정

- src/components/Space/SpaceForm.tsx
- src/components/common/Space/Space.tsx
> 스페이스 생성 시 카테고리 필수 알림 추가

- src/data/index.ts
Reverts Team-TenTen/LinkHub-FE#286
> Revert "[Release] v0.1.10"

- next.config.js
- next.config 파일의 images 경로 수정
> chore: images 경로 수정

- appspec.yml
> appspec.yml 수정

- package-lock.json
- package.json
> sharp 라이브러리 설치

- src/app/layout.tsx
> Metadata images 경로 수정

- src/app/(routes)/space/[spaceId]/page.tsx
- src/app/page.tsx
- src/components/common/LinkItem/LinkItemSkeleton.tsx
- src/components/common/MainSpaceList/MainSpaceList.tsx
- src/components/common/MainSpaceList/MainSpaceSkeleton.tsx
- src/components/common/Skeleton/Skeleton.tsx
- src/components/common/Space/SpaceSkeleton.tsx
#309 
- todos
- 댓글
- 스페이스폼
- 팔로우 리스트
> 스켈레톤 UI 개발 및 적용

- src/app/layout.tsx
> [Release] v0.1.16

- package-lock.json
- package.json
> sharp 라이브러리 삭제

- src/services/link/useLink.ts
> 인기 링크 조회 함수를 fetch로 변경

- package-lock.json
- package.json
> [Release] v0.1.18

- src/app/page.tsx
> [Release] v0.1.19
