src/app/globals.css, src/app/layout.tsx, src/components/common/Chip/Chip.tsx, src/components/common/Chip/constants/index.ts, src/components/index.ts, tailwind.config.ts
- close #4 
- Pretendard 폰트 적용
- Chip 컴포넌트 구현
```typescript
interface ChipProps {
label: string // 라벨 텍스트
color?: ChipColors // 색상 (default: 'emerald')
}
```
```typescript
type ChipColors = // Tailwind 색상 이름과 동일합니다.
| 'emerald'
| 'red'
| 'yellow'
| 'blue'
| 'indigo'
| 'purple'
| 'pink'
| 'gray'
```
```javascript
<Chip label="Tag" />
<Chip
label="Tag"
color="red"
/>
```
=> Chip 컴포넌트 구현

src/components/common/Toggle/Toggle.tsx, src/components/common/Toggle/hooks/useToggle.ts, src/components/index.ts
- close #15 
- Toggle 컴포넌트 구현
https://github.com/Team-TenTen/LinkHub-FE/assets/49032882/a6c1cbed-3408-4752-b9e8-1a34811ff2c5
```typescript
interface ToggleProps {
name: string
on?: boolean // 토글 여부 (default: false)
onChange: (e?: React.ChangeEvent<HTMLInputElement>) => void
}
```
```javascript
<Toggle
name="example"
onChange={(e) => {
console.log(e?.target.name)
}}
/>
```
=> Toggle 컴포넌트 구현

src/app/(routes)/register/page.tsx, src/components/UserInfoForm/UserInfoForm.tsx, src/components/UserInfoForm/hooks/useRegister.ts, src/components/common/Avatar/Avatar.tsx, src/components/common/Input/Input.tsx, src/data/index.ts, src/types/index.ts
#55 
- Input 컴포넌트의 button에 type이 없어 type='button'을 추가하였습니다.
- 사용자 프로필 수정 form에서 사용할 시 기존 데이터를 불러와 defaultValue로 넣어주었습니다.
- Avatar 컴포넌트에 className을 props로 받을 수 있도록 수정했습니다.
- User 데이터와 인터페이스를 사용자 프로필 수정 form에서 사용할 수 있도록 수정하였습니다.
=> 회원가입 페이지 구현

src/app/(routes)/login/page.tsx, src/components/Login/Login.tsx, src/components/Login/hooks/useLogin.ts
Closes #54 
- Todo: 카카오 로그인 토큰을 받아서 토큰이 db에 존재하면 로그인, 존재하지 않으면 회원가입페이지로 이동
=> 로그인 페이지 구현

next.config.js, src/app/(routes)/space/[spaceId]/setting/page.tsx, src/app/api/spaces/route.ts, src/app/page.tsx, src/components/Space/SpaceForm.tsx, src/components/UserInfoForm/UserInfoForm.tsx, src/components/common/CategoryList/CategoryList.tsx, src/components/common/CategoryList/CategoryListItem.tsx, src/components/common/CategoryList/constants/index.ts, src/components/common/Dropdown/constants/index.ts, src/constants/index.ts, src/data/index.ts, src/hooks/useHome.ts, src/hooks/useSearch.ts, src/services/space/spaces.ts, src/types/index.ts
- close #104 
메인 스페이스 조회 api 연결했습니다.
https://github.com/Team-TenTen/LinkHub-FE/assets/49032882/5f058282-4336-4349-bea9-7ddb931b781e
스페이스 조회 api response 타입을 추가했습니다.
```ts
export interface SpaceResBody {
spaceId: number
spaceName: string
description: string
userName: string // 아직 userName 없음
category: string
viewCount: number
scrapCount: number
favoriteCount: number
spaceImagePath: string
}
```
- 카테고리 옵션을 `type: [옵션_한글]`에서 `type: {옵션_한글: 옵션_영문}`으로 수정했습니다.
- CategoryList의 type은 기존과 동일한 방식으로 넘겨주시면 됩니다.
```ts
const DEFAULT = {
'엔터테인먼트•예술': 'enter_art',
'생활•노하우•쇼핑': 'life_knowhow_shopping',
'취미•여가•여행': 'hobby_leisure_travel',
'지식•이슈•커리어': 'knowledge_issue_career',
기타: 'etc',
}
export const CATEGORIES = {
default: DEFAULT,
all: { 전체: 'all', ...DEFAULT },
all_follow: { 전체: 'all', 팔로우: 'follow', …
```
=> 메인 스페이스 조회 api 연결

package-lock.json, package.json, src/app/(routes)/space/[spaceId]/comment/page.tsx, src/app/(routes)/space/[spaceId]/page.tsx, src/app/(routes)/user/[userId]/favorite/page.tsx, src/app/(routes)/user/[userId]/space/page.tsx, src/app/api/favorites/[spaceId]/route.ts, src/app/api/link/route.ts, src/app/api/space/[spaceId]/route.ts, src/components/common/Modal/LoginModal.tsx, src/components/common/Space/Space.tsx, src/components/common/Space/hooks/useFavorites.ts, src/constants/index.ts, src/lib/fetchAPI.ts, src/lib/fetchServerAPI.ts, src/services/favorites/favorites.ts, src/services/link/link.ts, src/services/meta/meta.ts, src/types/index.ts
#109 
- 좋아요 추가 api를 구현 및 적용하였습니다.
- 좋아요 취소 api를 구현 및 적용하였습니다.
token을 같이 전달해야만 즐겨찾기 여부값인 hasFavorite이 정상적으로 반환됩니다.
token 없이 요청하면 hasFavorite은 무조건 false로 옵니다.
<br>
로그인 알림 모달은 다른 곳에서도 많이 사용될 것 같아서 컴포넌트로 만들었습니다.
기존 useModal의 리턴값인 Modal, isOpen, modalClose만 전달하면 됩니다.
```tsx
const { Modal, isOpen, modalOpen, modalClose } = useModal()
...
return (
<LoginModal
Modal={Modal}
isOpen={isOpen}
modalClose={modalClose}
/>
)
```
<br>
제가 생각한 디바운스는 연속 클릭 할 때 별 아이콘, 숫자는 즉시 변경 -> 연속 클릭이 끝났을 때 마지막 api 한 번 호출인데,
현재 로직은 연속 클릭 할 때는 아무것도 변경되지 않음 -> 연속 클릭이 끝났을 때 아이콘, 숫자 변경 및 마지막 api 한 번 호출되고 있습니다.
제대로 적용했는지 여러분들의 생각을 코멘트에 적어주시면 감사하겠습니다!
<hr>
기범님께서 구현하신 회원가입 / 로그인 코드 pull 받아서 변경점 적용하였습니다.
ex) 쿠키 가져오는 로직, 로그인 여부 등
=> 스페이스 즐겨찾기 api 연결

src/app/(routes)/space/[spaceId]/page.tsx, src/app/api/link/delete/route.ts, src/app/api/space/[spaceId]/route.ts, src/app/page.tsx, src/components/common/LinkItem/LinkItem.tsx, src/components/common/LinkItem/hooks/useDeleteLink.ts, src/components/common/LinkList/LinkList.tsx, src/components/common/Space/hooks/useGetSpace.ts, src/components/common/Tab/utils/index.ts, src/services/link/link.ts
#118 
- 링크 삭제 api를 구현 및 연결하였습니다.
- 링크 조회 API가 없기 때문에 아래 보이는 링크 리스트는 mock 데이터입니다. 따라서 삭제해도 변하지 않고 API만 연결해 둔 상태입니다.
- 링크 조회 API가 나오면 실제 링크의 id로 연결 할 예정입니다. 
- useTab 훅에서 space의 isOwner의 값이 true일 때만 설정 탭이 보이도록 변경하였습니다. 
- isOwner의 값이 true일 때만 edit 버튼이 보이도록 수정하였습니다.
=> 링크 삭제 api 연결

src/app/(routes)/search/page.tsx, src/app/(routes)/user/[userId]/page.tsx, src/app/api/favorites/[spaceId]/route.ts, src/app/api/link/route.ts, src/app/api/user/[memberId]/followers/route.ts, src/app/api/user/[memberId]/following/route.ts, src/app/api/user/follow/route.ts, src/components/common/FollowList/FollowList.tsx, src/components/common/FollowList/hooks/useFollowQuery.ts, src/components/common/LinkItem/LinkItem.tsx, src/components/common/LinkItem/hooks/useLikeLink.ts, src/components/common/Space/Space.tsx, src/components/common/Space/hooks/useFavorites.ts, src/components/common/User/User.tsx, src/hooks/useFollowUser.ts, src/lib/fetchAPI.ts, src/lib/fetchServerAPI.ts, src/services/user/follow/route.ts
#140 
- 팔로잉 목록 조회 api를 연결 및 구현하였습니다.
- 팔로워 목록 조회 api를 연결 및 구현하였습니다.
- 무한 스크롤로 10개씩 페이지네이션 하였습니다.
(유저가 많이 없어서 page size를 3개로 설정한 후 확인해 보았습니다.)
- 본인의 프로필에서 팔로우 리스트를 클릭 후 팔로우 버튼을 누르면 count가 즉각적으로 바뀌도록 구현하였습니다.
<br>
GET 메소드를 제외한 모든 API 함수의 response 형식을 변경하였습니다.
```tsx
public async post(
endpoint: string,
body: any,
nextInit: RequestInit = {},
customHeaders: { [key: string]: string } = {},
type: string = 'default',
) {
const response = await fetch(`${this.baseURL}${endpoint}`, {
method: 'POST',
headers:
type === 'multipart'
? { ...customHeaders }
: { ...this.headers, ...customHeaders },
body: type === 'multipart' ? body : JSON.stringify(body),
...nextInit,
})
return response
}
```
<br>
반환값이 존재하는 API는 아래 형식으로 작성
```tsx
const response = await apiServer.post(path, {}, {}, headers)
const data = …
```
=> 팔로잉, 팔로워 목록 조회 api 연결

src/app/(routes)/space/[spaceId]/comment/page.tsx, src/app/api/space/[spaceId]/comments/[commentId]/route.ts, src/components/CommentList/CommentList.tsx, src/components/ReplyList/ReplyList.tsx, src/components/common/Comment/Comment.tsx, src/components/common/Comment/hooks/useComment.ts, src/hooks/useSpaceComment.ts, src/services/comment/comment.ts, src/types/index.ts
- close #144 
- 댓글 삭제 api 연결했습니다.
- 루트 댓글과 대댓글 모두 적용됩니다.
https://github.com/Team-TenTen/LinkHub-FE/assets/49032882/edbe93d8-f116-45e8-8df7-b07efc6e5742
- Comment 컴포넌트에서 댓글 삭제 로직을 처리하도록 수정했습니다.
- 댓글 삭제 모달을 컴포넌트로 이동하고, useComment 훅을 구현했습니다.
대댓글 로직 처리를 위해 parentCommentId 프로퍼티를 추가했습니다.
=> 댓글 삭제 api 연결

src/app/(routes)/search/page.tsx, src/app/api/user/search/route.ts, src/components/UserList/UserList.tsx, src/components/UserList/hooks/useUsersQuery.ts, src/components/common/SearchModal/SearchModal.tsx, src/components/common/SearchModal/constants/index.ts, src/services/user/search/search.ts, src/types/index.ts
- close #161 
- 유저 검색 api 연결했습니다.
- 무한 스크롤을 적용한 UserList 컴포넌트를 구현했습니다.
https://github.com/Team-TenTen/LinkHub-FE/assets/49032882/465ce662-d249-4d19-90e9-55ad41064d59
- useUsersQuery 훅으로 useInfiniteQuery를 제어합니다.
``` ts
interface UserListProps {
keyword: string // 📍 useInfiniteQuery에 들어가는 queryKey 옵션으로 유니크한 값
fetchFn: ({ pageNumber, pageSize }: SearchUserReqBody) => Promise<any> // 📍 유저 검색 fetch 함수
}
```
``` ts
return { users: data, fetchNextPage, hasNextPage } // useInfiniteQuery returns
```
- 검색 모달 인기 검색어를 준비 중으로 UI 변경했습니다.
=> 유저 검색 api 연결

src/app/api/links/route.ts, src/app/page.tsx, src/components/SpaceList/SpaceList.tsx, src/components/common/Sidebar/Sidebar.tsx, src/components/common/Tab/TabItem.tsx, src/components/common/ThemeButton/ThemeButton.tsx, src/hooks/useGetPopularLinks.ts, src/services/link/link.ts, src/types/index.ts, tailwind.config.ts
- close #162 
- 인기 링크 조회 api 연결했습니다.
- 메인 페이지 스페이스 모음에서 팔로우 카테고리를 제거했습니다.
- 스페이스 컴포넌트 카드 타입에 유저 이름을 적용했습니다.
https://github.com/Team-TenTen/LinkHub-FE/assets/49032882/4e32c1f1-7946-4d3c-bd6b-f60ac56ee148
- 테마 버튼 애니메이션 추가 및 시스템 테마 적용했습니다.
- 로그인 유무에 따라 로그아웃 버튼 표시되도록 수정했습니다.
=> 인기 링크 조회 api 연결

src/app/(routes)/space/[spaceId]/page.tsx, src/app/api/space/[spaceId]/links/route.ts, src/components/common/Input/Input.tsx, src/components/common/LinkItem/LinkItem.tsx, src/components/common/LinkItem/hooks/useDeleteLink.ts, src/components/common/LinkItem/hooks/useReadSaveLink.ts, src/components/common/LinkItem/hooks/useUpdateLink.ts, src/components/common/LinkList/LinkList.tsx, src/components/common/LinkList/constants/index.ts, src/components/common/LinkList/hooks/useCreateLink.ts, src/components/common/LinkList/hooks/useGetMeta.ts, src/components/common/Modal/Modal.tsx, src/components/common/Modal/hooks/useModalLogic.ts, src/components/common/Space/hooks/useGetTags.ts, src/components/common/SpaceMemberList/SpaceMemberList.tsx, src/services/link/link.ts
#105 
- 링크 수정 api를 연결 및 구현하였습니다.
- 링크 생성, 수정, 삭제 시 현재 태그 목록을 업데이트 하도록 구현하였습니다.
- 링크 생성, 수정 폼에 Validation을 적용하였습니다.
- 스페이스의 멤버가 링크를 클릭했을 때만 접속 이력 api가 호출되도록 수정하였습니다.
- 링크 접속 정보 프로필 이미지를 적용하였습니다.
- 스페이스 상세 조회 페이지에서 멤버 리스트 닉네임 클릭 시 프로필 페이지로 이동하도록 수정하였습니다.
<br>
태그 목록 조회 api를 react-query로 호출하는 로직으로 변경하였습니다.
태그 목록을 업데이트 하시려면 `refetchTags`를 사용하시면 됩니다.
```tsx
const useGetTags = ({ spaceId }: UseGetTagsProps): UseGetTagsReturnType => {
const { data, refetch: refetchTags } = useQuery({
queryKey: ['tagList', spaceId],
queryFn: () => fetchGetTags({ spaceId }),
enabled: !!spaceId,
})
return { tags: data?.tags, refetchTags }
}
```
=> 링크 수정 api 연결

src/app/(routes)/notification/invite/page.tsx, src/app/(routes)/notification/page.tsx, src/app/api/notification/invitations/route.ts, src/components/common/Header/Header.tsx, src/components/common/Notification/Notification.tsx, src/components/common/Notification/constants/index.ts, src/components/common/NotificationList/NotificationList.tsx, src/components/common/NotificationList/hooks/useNotificationQuery.ts, src/components/common/Tab/constants/index.ts, src/data/index.ts, src/services/notification/invitations.ts, src/types/index.ts
#178 
- 스페이스 초대 알림 조회 api를 연결 및 구현하였습니다.
- 무한 스크롤을 통해 10개씩 보이도록 적용하였습니다.
- 헤더의 알림 아이콘을 클릭할 때 초대 페이지로 이동하도록 변경하였습니다. (발표 전 임시로 변경)
- 알림 페이지의 탭 순서를 변경하였습니다. (초대를 앞으로)
스페이스 초대 알림 문구를 "~ 님이 ~에 초대했습니다." 로 변경하는 것이 좋을까요?
영상처럼 스페이스 이름에 "스페이스"가 붙으면 "스페이스 스페이스에 초대했습니다." 라고 보여져서요..!
=> 스페이스 초대 알림 조회 api 연결

src/app/(routes)/space/[spaceId]/page.tsx, src/components/common/LinkItem/LinkItem.tsx, src/components/common/Modal/NoneServiceModal.tsx
#173 
```tsx
{isCanEdit && (
<button
```
<br>
<br>
<br>
=> 링크 관련 버튼 수정

src/components/common/Header/Header.tsx, src/hooks/useModal.ts
#184 
- 중앙 모달, 사이드바 모달, 검색 모달을 사용할 때 뒷배경이 스크롤 되지 않도록 수정하였습니다.
=> 모달 외부 스크롤이 동작하는 버그 수정

src/components/Space/SpaceForm.tsx, src/components/UserInfoForm/UserInfoForm.tsx
#180 
1. 유저 닉네임은 2자 이상 10자 이하입니다.
2. 유저 닉네임에는 특수문자 및 공백이 포함될 수 없습니다.
3. 유저 한줄 소개는 50자 이하입니다.
4. 유저 이메일은 300자 이하입니다.
5. 스페이스명은 2자 이상 20자 이하입니다.
6. 스페이스 설명은 40자 이하입니다.
- 스페이스 생성
- 변경 전 : 스페이스를 생성하면 메인 화면으로 이동
- 변경 후 : 스페이스를 생성하면 생성된 스페이스로 이동
=> 스페이스폼, 유저폼 validation 추가

src/app/(routes)/space/[spaceId]/comment/page.tsx, src/components/common/Comment/Comment.tsx, src/components/common/Input/Input.tsx, src/hooks/useSpaceComment.ts
- close #180 
- 댓글 폼 validation에 토스트를 적용했습니다. (1000자 이하)
https://github.com/Team-TenTen/LinkHub-FE/assets/49032882/a1518153-9678-417d-ac7a-5d874fad6cb8
- 탈퇴한 유저인 경우 `profileImagePath: null` 이라서 아바타를 아예 보여주지 않게끔 예외 처리했습니다.
- 🔗 [Comment 컴포넌트 profileImagePath null 값 예외 처리](https://github.com/Team-TenTen/LinkHub-FE/commit/974877aec3214652d56a2e8f90701a0521a1c8ab)
- 지금은 탈퇴한 유저의 댓글에 대댓글을 달 수 있으나 추후 논의가 필요합니다.
- 버튼에 인풋 텍스트가 가려져 `inputButton = true`인 경우 padding-right를 추가했습니다.
- 🔗 [Input 컴포넌트 inputButton true인 경우 padding-right 추가](https://github.com/Team-TenTen/LinkHub-FE/commit/ed37d417c0573d467bfbf62677d1ff74704ad48d)
=> 댓글 폼 validation 토스트 적용

src/app/api/space/[spaceId]/route.ts, src/components/Space/SpaceForm.tsx, src/components/UserInfoForm/UserInfoForm.tsx, src/lib/fetchAPI.ts, src/services/space/space.ts
Closes #191 
```typescript
private async handleResponse(response: Response, type?: string) {
if (!response.ok) {
const data = await response.json()
switch (response.status) {
case 401:
notify('error', `${data.errorMessage}` || '인증되지 않은 사용자입니다.')
break
case 404:
notify('error', `${data.errorMessage}` || '해당하는 요청을 찾을 수 없습니다.')
break
case 500:
notify('error', `${data.errorMessage}` || '서버에 오류가 발생했습니다.')
break
default:
notify('error', `${data.errorMessage}` || '알 수 없는 오류가 발생했습니다.')
break
}
}
return type === 'delete' ? response : response.json()
}
```
```typescript
return this.handleResponse(response)
```
```typescript
// 스페이스 생성 예시
const { spaceId } = await feachCreateSpace(data, imageFile)
notify('info', '스페이스가 생성되었습니다.')
router.replace(`/space/${spaceId}`)
```
- next api route에서 get을 제외한 …
=> fetch error handler 추가

src/components/TagInput/TagInput.tsx, src/components/common/Input/Input.tsx, src/components/common/LinkItem/LinkItem.tsx, src/components/common/LinkList/LinkList.tsx, src/components/common/LinkList/constants/index.ts
#209 
<br>
<br>
<br>
<br>
- Input 컴포넌트의 테두리 색상이 제대로 적용되지 않는 문제를 발견하여 수정하였습니다.
- 링크가 카드 형식일 때 테두리를 slate3 색상으로 적용하였습니다.
=> 링크 수정 폼 validation 오류 수정

src/app/(routes)/space/[spaceId]/page.tsx, src/components/CommentList/CommentList.tsx, src/components/Space/SpaceForm.tsx, src/components/common/Space/Space.tsx, src/components/common/Space/hooks/useGetSpace.ts, src/components/common/Toggle/Toggle.tsx, src/types/index.ts
=> 스페이스 입력 폼 오류 수정

src/app/(routes)/notification/page.tsx, src/app/api/notification/[notificationId]/route.ts, src/components/SpaceList/SpaceList.tsx, src/components/common/Notification/Notification.tsx, src/components/common/NotificationList/NotificationList.tsx, src/components/common/NotificationList/constants/index.ts, src/components/common/NotificationList/hooks/useAcceptNotification.ts, src/components/common/NotificationList/hooks/useDeleteNotification.ts, src/components/common/NotificationList/hooks/useNotificationQuery.ts, src/services/notification/index.ts
#202 
<br>
<br>
<br>
멤버에 가입되어 있는 스페이스 알림을 수락할 시 에러 토스트가 2개가 보여져서 하나만 보이도록 수정하였습니다.
<br>
<br>
<br>
(이후에 올라온 댓글 로그인 알림 모달 적용 pr을 보고 댓글이 없을때 나타나는 텍스트의 스타일과 동일하게 수정하였습니다.)
<br>
<br>
<br>
(이후에 올라온 댓글 로그인 알림 모달 적용 pr을 보고 댓글이 없을때 나타나는 텍스트의 스타일과 동일하게 수정하였습니다.)
=> 알림 삭제 api 연결

src/components/TagInput/TagInput.tsx, src/services/link/link.ts
- close #204 
- 링크 수정 시 태그를 삭제하면 발생하는 버그를 수정했습니다.
- tagName, color가 없으면 body에 포함하지 않고 요청을 보내야 해서 fetch 함수를 수정했습니다.
- tagName은 `" "`을 허용하지 않기 때문에 trim()으로 입력 값의 앞뒤 공백을 제거했습니다.
https://github.com/Team-TenTen/LinkHub-FE/assets/49032882/34e16573-865e-4b0d-9310-1ec53e5f83c7
=> 링크 수정 버그 수정

src/app/api/notification/unchecked/route.ts, src/components/common/Header/Header.tsx, src/components/common/Header/hooks/useHeader.ts, src/services/notification/invitations.ts
- close #220 
- 헤더 알림 뱃지를 구현했습니다.
- 9개 초과 시 `9+`로 표시됩니다.
- 카운트를 보여주면 좋을 것 같아 아래와 같이 구현했습니다. 다른 의견 있으면 남겨주세요!
- 검색 아이콘을 수정했습니다.
- 로직 관련된 코드를 useHeader 커스텀 훅으로 분리했습니다.
=> 헤더 알림 뱃지 구현

src/components/Login/Login.tsx, src/components/UserInfoForm/UserInfoForm.tsx, src/components/UserInfoForm/hooks/useRegister.ts, src/components/common/Input/Input.tsx, src/components/common/Sidebar/hooks/useSidebar.ts, src/lib/fetchAPI.ts, src/services/email/index.ts
Closes #199 
- 알림 토스트의 영문 에러 메세지는 서버에서 반환해주는 에러메세지를 한글로 변경해달라고 요청드렸습니다.
```typescript
const {
register,
getValues,
setValue,
handleSubmit,
formState: { errors },
} = useForm<RegisterReqBody & EmailVerifyReqBody>({
defaultValues: {
nickname: userData?.nickname || '',
aboutMe: userData?.aboutMe || '',
newsEmail: userData?.newsEmail || '',
favoriteCategory: userData?.favoriteCategory || '',  // 회원가입시에 디폴트값은 빈 값
isSubscribed: userData?.isSubscribed || false,
},
})
```
```typescript
private async handleResponse(response: Response, type?: string) {
if (!response.ok) {
const data = await response.json()
switch (response.status) {
case 401:
notify('error', `${data.errorMessage}` || '인증되지 않은 사용자입니다.')
break
case 404:
notify('error', `${data.errorMessage}` || '해당하는 요청을 찾을 수 없습니다.')
break
case 500: …
```
=> 유저정보 form 버그 수정

src/app/globals.css, src/components/common/CategoryList/CategoryList.tsx, src/components/common/CategoryList/CategoryListItem.tsx, src/components/common/Sidebar/Sidebar.tsx
- close #249 
- 카테고리 리스트 컴포넌트가 horizotal인 경우 슬라이드를 적용했습니다.
https://github.com/Team-TenTen/LinkHub-FE/assets/49032882/9edb2434-acd6-4512-9e4e-823827e6c233
- Sidebar 컴포넌트 각 메뉴에 아이콘 추가했습니다.
=> CategoryList 컴포넌트 슬라이드 적용

src/components/common/LinkItem/LinkItem.tsx, src/components/common/LinkItem/hooks/useLikeLink.ts, src/components/common/LinkList/LinkList.tsx, src/components/common/LinkList/constants/index.ts, src/components/common/LinkList/hooks/useGetMeta.ts
#248 
- url에 백엔드 측과 동일한 프로토콜 형식만 가능하도록 validation을 추가하였습니다. (https, http, file만 가능)
- title에 빈 값을 넣었을 때 validation을 추가하였습니다.
<br>
- 좋아요를 클릭하고 다른 페이지를 이동했다가 다시 돌아오면 반영이 안 되어있던 문제를 수정하였습니다.
=> 링크 생성, 수정 폼 validation 조건 추가

src/app/layout.tsx, src/components/Login/Login.tsx, src/components/UserInfoForm/UserInfoForm.tsx, src/components/UserInfoForm/hooks/useRegister.ts
Closes #237 
- 카카오 provider와 socialId의 만료기한의 10분에서 5분으로 변경하였습니다.
=> 유저 정보 입력 폼 오류 수정

src/components/common/LinkItem/hooks/useLikeLink.ts
#259 
- 인기 링크 리스트에서 좋아요 버튼 클릭 시 api 호출이 되지 않는 오류를 수정하였습니다.
=> 인기 링크 리스트 좋아요 버튼 오류 수정

src/components/TagInput/TagInput.tsx, src/components/common/Dropdown/Dropdown.tsx, src/components/common/Sidebar/Sidebar.tsx
#264 
- 드롭다운 리스트, 태그 인풋, 사이드바, 의 스크롤 바를 안 보이게 수정하였습니다.
<br>
<br>
<br>
<br>
=> 드롭다운 목록 스타일 수정

src/app/api/meta/route.ts, src/components/common/LinkItem/LinkItem.tsx, src/components/common/LinkItem/hooks/useDeleteLink.ts, src/components/common/LinkItem/hooks/useUpdateLink.ts, src/components/common/LinkList/LinkList.tsx, src/components/common/LinkList/hooks/useCreateLink.ts, src/components/common/LinkList/hooks/useGetMeta.ts
#276 
네이버 블로그와 같은 iframe으로 이루어진 사이트는 메타 데이터를 가져오지 못하는 문제를 해결하였습니다.
`https://` `http://` `file://` 프로토콜 형식은 지키면서
존재하지 않는 url을 입력 시에도 title 인풋의 disabled를 false로 변경하였습니다. (대신 제목에 아무것도 들어가지 않음)
링크 생성 버튼을 빠르게 클릭 시 링크가 중복해서 생성되는 문제가 발생해서
링크 생성, 수정, 삭제, 메타 데이터 가져오는 버튼을 api 호출 중일 때 중복 클릭할 수 없도록 구현하였습니다.
메타 데이터를 가져올 때와 링크 생성, 수정, 삭제 시 로딩 스피너를 추가하였습니다.
=> open-graph-scraper 예외 추가

package-lock.json, package.json, src/components/Space/SpaceForm.tsx, src/components/UserInfoForm/UserInfoForm.tsx, src/components/common/SearchModal/SearchModal.tsx, src/components/common/SearchModal/hooks/useSearchModal.ts, src/hooks/useProfileSpacesSearch.ts
#282 
- `browser-image-compression` 라이브러리를 사용해서 용량이 큰 이미지일 경우 사이즈를 압축해서 전송하는 것으로 변경하였습니다. (413 에러 해결)
```tsx
const resizingBlob = await imageCompression(e?.target.files[0], {
maxSizeMB: 0.5, // 이미지가 0.5MB 보다 크면 압축을 진행
})
setImageFile(resizingBlob)
```
영운님께서 검색 로직에 `MySQL Full Text Search`를 도입한다고 하셔서 검색 요구 사항이 조금 변경되었습니다.
토스트 알림으로 예외 처리 추가
<br>
아무것도 입력하지 않았을 때 전체 스페이스 or 전체 유저가 나오도록 required를 삭제하였습니다.
=> 이미지 용량 최적화

src/app/page.tsx, src/components/SpaceList/hooks/useMainSpacesQuery.ts, src/components/common/MainSpaceList/MainSpaceList.tsx, src/services/space/spaces.ts, src/services/user/profile/favorites.ts, src/types/index.ts
#289 
- 기존 `오프셋 기반 페이지네이션(Offset-based Pagination)`이 적용되었던 메인 페이지의 스페이스 리스트를 `커서 기반 페이지네이션(Cursor-based Pagination)` 방식으로 변경하였습니다.
- 메인 페이지, 검색 페이지, 프로필 페이지에서 스페이스 검색 로직이 공통적으로 사용되고 있어서 메인 페이지만 변경할 수 있도록 `useMainSpacesQuery` `MainSpaceList`를 추가로 구현하였습니다.
기존 API request 값
```ts
{
pageNumber: number,
pageSize: number,
sort: string,
filter: string,
}
```
<br>
변경 후 API request 값
```ts
{
lastFavoriteCount: number,
lastSpaceId: number,
pageSize: number,
sort: string,
filter: string,
}
```
Cursor-based Pagination 관련 글인데 궁금하시면 한 번 읽어봐도 좋을 것 같습니다!
[관련 블로그](https://velog.io/@minsangk/%EC%BB%A4%EC%84%9C-%EA%B8%B0%EB%B0%98-%ED%8E%98%EC%9D%B4%EC%A7%80%EB%84%A4%EC%9D%B4%EC%85%98-Cursor-based-Pagination-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0)
=> 스페이스 필터 조회 로직 수정

src/components/common/CategoryList/CategoryList.tsx, src/components/common/CategoryList/CategoryListItem.tsx, src/components/common/Comment/Comment.tsx, src/components/common/Header/Header.tsx, src/components/common/LinkItem/LinkItem.tsx, src/components/common/Space/Space.tsx
#305 
불필요하게 리렌더링되는 컴포넌트 메모이제이션하였습니다.
=> 불필요하게 리렌더링되는 컴포넌트 메모이제이션

.gitignore, next.config.js, package-lock.json, package.json, src/app/(routes)/notification/page.tsx, src/app/(routes)/space/[spaceId]/comment/page.tsx
#311
- `@next/bundle-analyzer`를 사용해 번들 파일의 크기를 시각화 하여 유독 사이즈가 큰 번들파일을 줄이고자 시도하였습니다.
<br><br>
=> js 번들링 사이즈 감소
